# Setup
name:         KawShon Blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
