# Setup
name:         KawShon
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/kawshonblog"
locale:       "en"

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
